[package]
name = "msg_template"
version = "0.1.0"
authors = ["Jacky <964413011@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
